def mavenCommand = '$MVN_CMD -Duser.home=/var/maven -B clean test site site:stage -DstagingDirectory=$(pwd)/target/staging1/$(basename $(dirname $JOB_NAME)) install -Dsurefire.timeout=1000' 

pipeline {
  options {
    buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '130'))
    disableConcurrentBuilds()
  }
  triggers {
    pollSCM('H H/3 * * *') // Poll for changes every three (3) hours
    snapshotDependencies()
    cron('H H H H/2 *') // Run unconditionally every other month
  }
  agent none
  stages {
    stage('Matrix') {
      matrix {
        agent {
          docker {
            image "maven:3-${JAVAVERSION}"
            args '-v maven-repo-matrix:/var/maven/.m2 -e MAVEN_CONFIG=/var/maven/.m2'
          }
        }
        axes {
          axis {
            name 'JAVAVERSION'
            values 'ibmjava-8',
                   'amazoncorretto-8', 'amazoncorretto-11', 'amazoncorretto-17',
                   'amazoncorretto-19', 'amazoncorretto-20', 'amazoncorretto-21'
          }
          axis {
            name 'COMPILESOURCE'
            // Skipping in-between compilesource versions
            values '7', '8', '9', '11', '17', '19', '21'
          }
        }
        excludes {
          // Newer versions of openjdk hangs
          exclude {
            axis { 
              name 'JAVAVERSION'
              values 'amazoncorretto-19', 'amazoncorretto-20'
            }
          }
          
          // This simply takes too much time to compile,
          // I will do this in steps:
          // 7 -> ?
          exclude {
            axis {
              name 'COMPILESOURCE'
              values '9', '11', '17', '19', '21'
            }
          }
          exclude {
            // Older versions doesn't support new compilesource.
            axis { 
              name 'JAVAVERSION'
              values 'ibmjava-8',
                     'amazoncorretto-8'
            }
            axis {
              name 'COMPILESOURCE'
              values '9', '11', '17', '19', '21'
            }
          }
          exclude {
            // Older versions doesn't support new compilesource.
            axis { 
              name 'JAVAVERSION'
              values 'amazoncorretto-11'
            }
            axis {
              name 'COMPILESOURCE'
              values '17', '19', '21'
            }
          }
          exclude {
            // Older versions doesn't support new compilesource.
            axis { 
              name 'JAVAVERSION'
              values 'amazoncorretto-17'
            }
            axis {
              name 'COMPILESOURCE'
              values '19', '21'
            }
          }
          exclude {
            // Newer jdk version doesn't support old compilesource
            axis {
              name 'JAVAVERSION'
              values 'amazoncorretto-20', 'amazoncorretto-21'
            }
            axis {
              name 'COMPILESOURCE'
              values '7'
            }
          }
        }
        stages {
          stage('build and install') {
            steps {
              waitForNetwork()
              timeout(time: 1, unit: 'HOURS') {
                checkout scm

                // Patch to get another set of artifacts.
                // This relies on the order of the lines with groupId and artifactId.
                sh "find . -name target -type d -prune -o -name pom.xml -type f -print | while read pom; do sed '\$!N;s,<groupId>\\(org.argouml</groupId>.*\\n.*<artifactId>[^j]\\),<groupId>${JAVAVERSION}-${COMPILESOURCE}.\\1,;P;D' -i \$pom; done"
                
                sh "find . -name target -type d -prune -o -name pom.xml -type f -print | while read pom; do sed 's,\\(<compileSource>\\)1.7\\(</compileSource>\\),\\1${COMPILESOURCE}\\2,' -i \$pom; done"
              }
              waitForNetwork()
              timeout(time: 3, unit: 'HOURS') {
                withMaven(mavenSettingsConfig: 'github') {
                  sh "${mavenCommand}"
                }
              }
            }
          }
        }
        post {
          always {
            cleanWs cleanWhenAborted: false,
                    cleanWhenFailure: false,
                    cleanWhenNotBuilt: false,
                    cleanWhenUnstable: false,
                    deleteDirs: true,
                    notFailBuild: true,
                    patterns: [[pattern: 'target/**', type: 'INCLUDE']]
          }
        }
      }
    }
  }
}

def waitForNetwork() {
  waitUntil {
    return sh(returnStatus: true, script: 'curl https://github.com/robots.txt > /dev/null') == 0
  }
}
