pipeline {
  agent {
    dockerfile {
      filename 'jobs/create_agent_image/Dockerfile'
      additionalBuildArgs '--tag myjenkinsagent:latest'
    }
  }
  stages {
    stage('Noop') {
      steps {
        sh 'java -version'
      }
    }
  }
}
