pipeline {
  agent {
    label 'master'
  }
  stages {
    stage('Create') {
      steps {
        dir('jobs/create_agent_image') {
          sh 'docker build . --tag myjenkinsagent:latest'
        }
      }
    }
  }
}
