node ('docker_image_creator') {
  deleteDir()
  checkout scm
  dir("dockerfiles") {
    dirs = sh (script: "echo */", returnStdout: true).trim()

    dirs.split(" ").each { dockerfilename ->
      dir = dockerfilename.split("/")[0]

      stage("$dir") {
        dir ("$dir") {
          sh "test -f Dockerfile || echo FROM maven:$dir > Dockerfile"
          docker.build("my_fixed_maven:$dir", "--pull .1")
        }
      }
    }
  }
}
