node {
  deleteDir()
  checkout scm
  dir("dockerfiles") {
    files_list = sh (script: "ls */Dockerfile", returnStdout: true).trim()

    files_list.split("\\r?\\n").each { dockerfilename ->
      dir = dockerfilename.split("/")[0]

      stage("$dir") {
        // Creating and running the first one
        dir ("$dir") {
          sh "test -f Dockerfile || echo FROM maven:$dir > Dockerfile"
          sh "pwd" // docker build -t my_fixed_maven:$dir
        }
      }
    }
  }
}
