services:
    docker:
        restart: always
        image: docker:dind
        volumes:
          - jenkins-docker-certs:/certs/client
          - jenkins-data:/var/jenkins_home
          - maven-repo:/var/maven-repo
          - maven-repo-matrix:/var/maven-repo-matrix
        environment:
          - 'DOCKER_TLS_CERTDIR=/certs'
        ports:
          - '2376:2376'
        privileged: true
        command: ["sh", "-c", "dockerd-entrypoint.sh & sleep 20 && docker run --rm -v /var/maven-repo:/m1 -v /var/maven-repo-matrix:/m2 maven:3-amazoncorretto-17 chown 1000:1000 /m1 /m2 && wait"]

    myjenkins:
        restart: on-failure
        build: .
        depends_on:
          - docker
        environment:
          - 'DOCKER_HOST=tcp://docker:2376'
          - 'DOCKER_CERT_PATH=/certs/client'
          - 'DOCKER_TLS_VERIFY=1'
        ports:
          - '8080:8080'
          - '50000:50000'
        volumes:
          - jenkins-data:/var/jenkins_home
          - jenkins-docker-certs:/certs/client:ro


volumes:
  jenkins-data:
    external: true
  jenkins-docker-certs:
    external: true
  maven-repo:
  maven-repo-matrix:
