Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = "jenkins"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.name = "argouml-jenkins"
    vb.gui = false
    vb.cpus = 2
    vb.memory = "4096"
  end

  # python2 is required for jenkins_jobs in ansible. python3 has a bug.
  config.vm.provision "shell", inline: "which python || sudo apt -y install python"

  config.vm.define :jenkins do |jenkins|
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/jenkins.yml"
    end
  end
end
