#!groovy

// This is a Pipeline job configured with the following settings:
// Log rotation
// * Days to keep build: 100
// * Max # of builds to keep 5
// Build Trigger
// Gerrit event
// * Server: GerritHub
// * TriggerOn:
// ** Patchset Created
// * Gerrit Project
// ** Type: Path argouml-tigris-org/parentpom
// ** Branch: Plain master

// The file contains some assumptions on how the build machine is set up.
// See https://github.com/argouml-tigris-org/argouml/wiki/Jenkins-configuration

def changeBranch = "change-${GERRIT_CHANGE_NUMBER}-${GERRIT_PATCHSET_NUMBER}"
def local_volume = "maven-repo-${changeBranch}"
def inside_params1 = "-v /var/maven-repo:/var/maven/maven-repo " +
  "-v ${local_volume}:/var/maven/.m2"

image = 'maven:3-ibmjava-8'
inside_params = "${inside_params1} -e MAVEN_CONFIG=/var/maven/.m2"

def buildrepo(repo) {
  stage(repo) {
    timeout(time:3, unit: 'HOURS') {
      node {
        sh "git clone https://github.com/argouml-tigris-org/${repo}.git"
        docker.image(image).inside(inside_params) {
          withMaven() {
            dir (repo) {
              sh '$MVN_CMD -Duser.home=/var/maven -B compile test site install'
            }
          }
          // Clean everything
          deleteDir()
        }
      }
    }
  }
}

node {
  // This is the same as for the gerrit project
  stage('checkout') {
    checkout([
      $class: 'GitSCM',
      branches: [[name: '*/master']],
      extensions: [
        [$class: 'BuildSingleRevisionOnly'],
        [$class: 'CleanBeforeCheckout', deleteUntrackedNestedRepositories: true]
      ],
      userRemoteConfigs: [[
        name: '${GERRIT_PROJECT}',
        url: 'https://github.com/${GERRIT_PROJECT}'
      ]],
      changelog: false,
      poll: false
    ])

    // Fetch the changeset to a local branch using the build parameters
    // provided to the build by the Gerrit plugin...
    sh "git fetch ${GERRIT_PROJECT} ${GERRIT_REFSPEC}:${changeBranch}"
    sh "git checkout ${changeBranch}"
  }

  stage('set up repository') {
    // This will install stuff in the maven repo, to avoid polluting it with
    // not approved stuff, lets make a local copy, reusing whatever was in the
    // maven-repo from other builds.

    sh "docker run --rm ${inside_params1} ${image} " +
      "chown 1000:1000 /var/maven/.m2"
    sh "docker run --rm -u 1000:1000 ${inside_params1} ${image} " +
      "cp -rp /var/maven/maven-repo/repository /var/maven/maven-repo/settings-docker.xml /var/maven/.m2"
  }

  stage('parentpom') {
    timeout(time:1, unit: 'HOURS') {
      docker.image(image).inside(inside_params)  {
        withMaven() {
          sh '$MVN_CMD -Duser.home=/var/maven -B compile test site install'
        }
        // Clean everything
        deleteDir()
      }
    }
  }
}

buildrepo('argouml')
buildrepo('test-i18n-properties')
buildrepo('argouml-cpp')

def buildMap1 = [:]
def buildMap2 = [:]

node {
  // For the rest of the projects used, checkout master
  stage('manifest') {
    sh 'git clone https://github.com/argouml-tigris-org/manifest.git'
    sh "grep project manifest/default.xml | " +
      "grep -v parentpom | " +
      "grep -v /project | " +
      "sed 's/.*name=.\\([^ ]*\\). .*/\\1/;!d' | " +
      "grep -vx testmodels | " +
      "grep -vx tools | " +
      "grep -vx argouml-documentation | " +
      "grep -vx argopdf | " +
      "grep -vx argouml-andromda | " +
      "grep -vx argouml-db | " +
      "grep -vx argouml-enki | " +
      "grep -vx argouml-graphviz | " +
      "grep -vx argouml-model-checker | " +
      "grep -vx argouml-pattern-wizard | " +
      "grep -vx argouml-ruby | " +
      "grep -vx argouml-xtuml | " +
      "grep -vx argouml-xsd > projects.lst"
  }
  
  def i18n_list = sh (
    script: 'grep i18n projects.lst | grep -vx test-i18n-properties',
    returnStdout: true).trim().split("\\r?\\n")
  i18n_list.each { repo ->
    buildMap1[repo] = {
      buildrepo(repo)
    }
  }

  def other_list = sh (
    script: 'grep -v i18n projects.lst | ' +
    'grep -vx argouml | ' +
    'grep -vx argouml-cpp | ' +
    'grep -vx test-i18n-properties',
    returnStdout: true).trim().split("\\r?\\n")
  other_list.each { repo ->
    buildMap2[repo] = {
      buildrepo(repo)
    }
  }
}

parallel(buildMap1)

parallel(buildMap2)
