#!groovy

// This is a Pipeline job configured with the following settings:
// Log rotation
// * Days to keep build: 100
// * Max # of builds to keep 5
// Build Trigger
// Gerrit event
// * Server: GerritHub
// * TriggerOn:
// ** Patchset Created
// * Gerrit Project
// ** Type: Path argouml-tigris-org/parentpom
// ** Branch: Plain master

// The file contains some assumptions on how the build machine is set up.
// See https://github.com/argouml-tigris-org/argouml/wiki/Jenkins-configuration

def getItem(String name) {
  for (int i in manifest.project) {
    if (manifest.project[i].@name == 'name') {
      return manifest.project[i]
    }
  }
  return null
}

def changeBranch = "change-${GERRIT_CHANGE_NUMBER}-${GERRIT_PATCHSET_NUMBER}"

def buildrepo(inside_params, repo) {
  print(repo)
//   stage(repo) {
//     timeout(time:1, unit: 'HOURS') {
//       env.inside(inside_params) {
//         withMaven() {
//           sh "git clone https://github.com/argouml-tigris-org/${repo}.git"
//           dir (repo) {
//             sh '$MVN_CMD -Duser.home=/var/maven -B compile test site install'
//           }
//         }
//       }
//     }
//   }
}

node {
  
  // This is the same as for the gerrit project
  stage('checkout') {
    checkout([
      $class: 'GitSCM',
      branches: [[name: '*/master']],
      extensions: [
        [$class: 'BuildSingleRevisionOnly'],
        [$class: 'CleanBeforeCheckout', deleteUntrackedNestedRepositories: true]
      ],
      userRemoteConfigs: [[
        name: '${GERRIT_PROJECT}',
        url: 'https://github.com/${GERRIT_PROJECT}'
      ]],
      changelog: false,
      poll: false
    ])

    // Fetch the changeset to a local branch using the build parameters provided to the
    // build by the Gerrit plugin...
    sh "git fetch ${GERRIT_PROJECT} ${GERRIT_REFSPEC}:${changeBranch}"
    sh "git checkout ${changeBranch}"
  }

  // This will install stuff in the maven repo, to avoid polluting it with
  // not approved stuff, lets make a local copy, reusing whatever was in the
  // maven-repo from other builds.

  def image = 'maven:3-ibmjava-8'
  def local_volume = "maven-repo-${changeBranch}"
  def inside_params1 = "-v /var/maven-repo:/var/maven/maven-repo -v ${local_volume}:/var/maven/.m2"
  def inside_params = "${inside_params1} -e MAVEN_CONFIG=/var/maven/.m2"
  sh "docker run --rm ${inside_params1} ${image} chown 1000:1000 /var/maven/.m2"
//  sh "docker run --rm -u 1000:1000 ${inside_params1} ${image} cp -rp /var/maven/maven-repo/repository /var/maven/maven-repo/settings-docker.xml /var/maven/.m2"
  def env = docker.image(image)

//  stage('parentpom') {
//    timeout(time:1, unit: 'HOURS') {
//      env.inside(inside_params)  {
//        withMaven() {
//          sh '$MVN_CMD -Duser.home=/var/maven -B compile test site install'
//        }
//        // Clean everything
//        deleteDir()
//      }
//    }
//  }

  // For the rest of the projects used, checkout master
  stage('manifest') {
    sh 'git clone https://github.com/argouml-tigris-org/manifest.git'
    sh "grep project manifest/default.xml | grep -v parentpom | grep -v /project | sed 's/.*name=.\\([^ ]*\\). .*/\\1/;!d | grep -vx testmodels | grep -vx tools | grep -vx argouml-documentation | grep -vx argopdf | grep -vx argouml-andromda | grep -vx argouml-db | grep -vx argouml-enki | grep -vx argouml-graphviz | grep -vx argouml-model-checker | grep -vx argouml-pattern-wizard | grep -vx argouml-ruby | grep -vx argouml-xtuml | grep -vx argouml-xsd' > projects.lst"
  }
  
  buildrepo(inside_params, 'argouml')
  buildrepo(inside_params, 'test-i18n-properties')
  buildrepo(inside_params, 'argouml-cpp')
  def buildMap1 = [:]
  def i18n_list = sh (script: 'grep i18n projects.lst | grep -vx test-i18n-properties', returnStdout: true).trim().split("\\r?\\n")
  i18n_list.each { repo ->
    buildMap1[repo] = {
      buildrepo(inside_params, repo)
    }
  }
  parallel(buildMap1)

  def buildMap2 = [:]
  def other_list = sh (script: 'grep -v i18n projects.lst | grep -vx argouml | grep -vx argouml-cpp | grep -vx test-i18n-properties', returnStdout: true).trim().split("\\r?\\n")
  other_list.each { repo ->
    buildMap2[repo] = {
      buildrepo(inside_params, repo)
    }
  }
  parallel(buildMap2)
}
